### ISSUE TITLE
LEAVE_VISIBILITY dont work

### ISSUE THREAD

**Issue by FaNNboii** [svenpaulsen/ts3client-notification-plugin#3]
Hey, LEAVE_VISIBILITY dont work for me. I dont get a Notification if buddy disconnect from teamspeak.

**Comment by svenpaulsen** [comment]
You're right... in this case, the client is already gone and the plugin is unable to request the necessary variables from the server to determine whether or not the user is on your friends list. I guess I'll somehow need to manage a cached list of connected friends in the plugin so that information is always available.

For now, I've removed the non-functional code and released a new build as version 1.0.3.

**Comment by svenpaulsen** [comment]
Please re-test with the latest 1.0.4 build...

https://github.com/svenpaulsen/ts3client-notification-plugin/releases/tag/1.0.4
